name: 'Habitica Readme'
author: Oleksandr Yalovyi
description: '🚧 Updates README with your Habitica stats'

inputs:
  HABITICA_USER_ID:
    description: 'Your Habitica User ID'
    required: true

  HABITICA_TOKEN:
    description: 'Your Habitica API Token'
    required: true

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "activity"
  color: "blue"
